### ISSUE TITLE
Remove support for the short style

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#1613]
The formatter is in a transition period from the older "short" formatting style to the new "tall" style. It currently supports both styles and uses the language version of the file to determine which style you get. Eventually, we want to remove support for the old style completely so we no longer need to maintain that code. This issue tracks that.

Here are the tasks to remove the old style:

- [ ] **Decide what version of the Dart SDK will no longer support the short style.** Coordinate with leads and PMs to decide when we want to remove support.
- [ ] **Announce the intent to stop supporting the older style.** Send a notification on all the various channels letting users know that the upcoming Dart SDK release will change the formatting of their older language versioned files. Encourage users to preemptively configure their project to use the new style on all of their files to minimize disruption.
- [ ] **Remove support for short style.** Delete the old AST visitor, Chunk internal representation, line splitter, and short style tests. Rejoice at the simpler, cleaner formatter codebase.
- [ ] **Roll it into the Dart SDK.**

**Comment by munificent** [comment]
It may make the most sense to tie this to Dart 4. See: https://github.com/dart-lang/language/issues/4703

**Comment by FMorschel** [comment]
OOC, do we have any numbers (like %) of projects (even from pub) to know the ratio between the two styles? I'd also be interested in the use of preservation of commas. If that is not as widely used as it was originally requested, than it could be a sign for us to drop support for it too.

**Comment by munificent** [comment]
That's a good question. We should definitely be able to get data about the language versions of what's on pub, but I don't know if anyone on the team has made that accessible. Getting data about language version for applications not on pub might be harder. I know we gather some amount of opt-in telemetry, but I haven't looked at it.

The formatter doesn't track any data, so doesn't report telemetry for things like trailing commas, but analyzer might. We should be able to get that data from published pub packages.
