### ISSUE TITLE
Support NNBD syntax

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#536]
Format and test all of the new syntax added for NNBD:

* [x] Nullable type (`Type?`) (#846)
* [x] Nullable function-typed parameters (`function(param()?) { ... }`) (#846)
* [x] Null-assertion operator (postfix `!`) (#832)
* [x] Null-aware cascade (`?..`) (#848)
* [x] Null-aware index operator (`obj?.[index]`)
* [x] `required` parameter modifier (#847)
* [x] `late` modifier on variables and members (#845)

**Comment by munificent** [comment]
Null-assertion operators are handled by: https://github.com/dart-lang/dart_style/pull/832

cc @leafpetersen

**Comment by munificent** [comment]
OK, all these changes have landed. I'm going to see if there are any other quick bug fixes I can get in and then I'll cut a new release.
